server:
  port: 7000
  servlet:
    context-path: /sponsor

spring:
  application:
    name: eureka-client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://47.106.168.17:3306
    username: springcloud_ad
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456


eureka:
  client:
    service-url:
     defaultZone: http://eureka-server1:4396/eureka/
