server:
  port: 80

spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:4396/eureka/
  instance:
    instance-id: ad-gateway-80
    prefer-ip-address: true
zuul:
  prefix: /yangxp
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
  strip-prefix: false

